services:
  stress:
    container_name: stress
    restart: always
    image: jancunha/stress:v1
    ports: 
      - 8080:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
